### ISSUE TITLE
cannot set 2 A records

### ISSUE THREAD

**Issue by ericlenio** [lmammino/godaddy-dns#10] opened 2016-10-10 10:54 UTC
My config:
```
{
  "apiKey":"xxx",
  "secret":"xxx",
  "domain":"example.com",
  "records":[
    {"name":"cloud1","type":"A","ttl":3600},
    {"name":"ltc","type":"A","ttl":3600}
  ]
}
```

when I run this I see:

`[Mon Oct 10 2016 10:49:43 GMT+0000 (UTC)] Failed request to GoDaddy Api Another record with the same attributes already exists`

The "ltc" record does get properly set, but not "cloud1". Basically, I want 2 A records pointing to the same IP. Any thoughts?

**Comment by lmammino** [comment] 2016-10-19 21:55
This seems to have been resolved by https://github.com/lmammino/godaddy-dns/pull/11.
The new version is available on NPM.

@ericlenio feel free to re-open this if the issue is still standing for you.

**Closed by lmammino** 2016-10-19 21:55 UTC

**Comment by ericlenio** [comment] 2016-10-27 17:11
Works now, I successfully updated 3 "A" records that all pointed to the same IP. Thanks.
